
import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import "./globals.css";
import localFont from 'next/font/local'
import { myFont } from "./staticFonts/fonts";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // console.log(myFont.);

  return (
    <html lang="en">
      <body className={`${myFont.variable} font-sans `}>{children}</body>
    </html>
  );
}
